### PR TITLE
[DO NOT MERGE] Updating 'che-plugin-registry' to the latest 7.20.1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
eclipse/che#18168

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
