### PR TITLE
Updating che.openshift.io to the latest 7.0.0-RC-1.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/redhat-developer/rh-che/issues/1412

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please provide +1 / -1 for the prod update to 7 CR1 version

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
I've checked basic behaviour for Che 6 and Che 7 workspace, seems to work fine. I found only one weird thing, when creating vert-x Che 6 workspace, I see this in UI. It says that the workspace is not compatible and even the message is not readable. 

Screenshot from 2019-06-04 07-59-12

**Comment by ibuziuk** [comment]
@Katka92 you can find more details about the `incompatible format` message in the https://github.com/eclipse/che/issues/12917
Please, approve the PR if  no other issues were caught by testing and we are ready for CR1 update on prod

**Pull request merged**
