### PR TITLE
[DO NOT MERGE] Updating Hosted Che to the latest 7.14.2 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Upstream issue eclipse/che#17111

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
The first one failed on LS initializatino that took too long.
Last two tests failed on long worksapce startup - more then 3 minutes [1] [2].

[1] 
Screenshot from 2020-06-17 14-05-22

[2]
Screenshot from 2020-06-17 14-07-02

**Comment by Katka92** [comment]
[pre-release-tests]

**Comment by Katka92** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
Pre-release tests results:
 - Go failed on Application not available
 - Java Maven failed on long workspace startup, long LS initialization
 - Java Vert.x workspace startup and LS (both seems like some glitch)
 - factory test - long workspace startup

I'll rerun the suite again.

**Comment by Katka92** [comment]
Pre-release test job could not obtain user token. Running again.
[pre-release-tests]

**Comment by ibuziuk** [comment]
Closed in favour of https://github.com/openshiftio/saas-openshiftio/pull/1435

**Pull request closed without merging**
