### PR TITLE
Updating che on prod to the latest 6.18.1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
cc @rhopp @ScrewTSW

**Comment by ScrewTSW** [comment]
project pull issue on starter-us-east-2a cluster: https://github.com/redhat-developer/rh-che/issues/1248

**Comment by ibuziuk** [comment]
@ScrewTSW isn't it known https://github.com/openshiftio/openshift.io/issues/4695 ?

**Comment by ScrewTSW** [comment]
The regression seems to be gone, the workpsaces are being stopped successfully after the timeout

**Comment by ibuziuk** [comment]
@ScrewTSW @rhopp it would be great to get info about things that are not covered by e2e / PR check test:
- idling
- che 7

**Comment by rhopp** [comment]
@ibuziuk 
afaik the e2e tests just check workspace (che 6 based) creation. Nothing more...

**Comment by ScrewTSW** [comment]
> @ibuziuk
> afaik the e2e tests just check workspace (che 6 based) creation. Nothing more...

:+1:

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW that is why I wrote about idling & che 7 that are NOT covered by any of existing tests and expect them to be tested manually before +1 / -1 of the PR

**Comment by ScrewTSW** [comment]
@ibuziuk The workspaces are behaving normally on other clusters (excluding starter-us-east-2a where the project import issue is present). The workspace stopping is functional. We agreed with @rhopp to :+1: the PR as the project import issue is a platform issue.

**Pull request merged**
