### PR TITLE
bring cache enhancement to prod

### PR DESCRIPTION
**Pull request by nurali-techie**
PR - https://github.com/fabric8-services/fabric8-oso-proxy/pull/56

### CODE REVIEW

**Comment by nurali-techie** [comment]
[test]

**Comment by Katka92** [comment]
Test passed, this fail you can see is bug in a test. LGTM

**Comment by nurali-techie** [comment]
@l0rd or someone responsible, request to merge this PR.

**Comment by nurali-techie** [comment]
@alexeykazakov thanks for merging :-)

**Pull request merged**
