### PR TITLE
Updating rh-che to the latest 7 beta 2 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW please provide QA approval before promoting the change to master

**Comment by ibuziuk** [comment]
should be merged only once prod cm is updated - https://gitlab.cee.redhat.com/service/app-interface/merge_requests/252/diffs

**Comment by ibuziuk** [comment]
hmm.. for me workspace is not started against free-stg and there is a bunch of 

> {"@timestamp":"2019-03-25T18:57:25.854+00:00","@version":1,"message":"Processing messing within unidentified session","logger_name":"org.eclipse.che.api.core.websocket.impl.BasicWebSocketEndpoint","thread_name":"http-nio-8080-exec-6","level":"WARN","level_value":30000}

image


might be related to infra issues, but I'm not sure about that.

**Comment by ibuziuk** [comment]
ok, looks infra related - was able to start workspace successfully against 2a. Waiting for QA approval before promoting to prod

**Comment by Katka92** [comment]
I've tried to create workspace, run vertx-http-booster project, click preview URL, change the code and see if preview has changed too. All that worked fine, so +1 for updating prod.

**Pull request merged**
