### PR TITLE
[DO NOT MERGE] Updating Hosted Che to the latest '7.24.1' upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/eclipse/che/issues/18770

### CODE REVIEW

**Comment by Katka92** [comment]
[pre-release-tests]

**Comment by Katka92** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
@Katka92 just for the record there are Quarkus / Scala known issues that affect the pre-release-suite
 - https://github.com/eclipse/che/issues/18663
 - https://github.com/eclipse/che/issues/18662
 Would be great to prioritize those for `7.25.0`

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
``` 
144 passing (39m)
  2 pending
  2 failing
```
2 failing are the known Quarkus and Scala:
- eclipse/che#18663
- eclipse/che#18662

**Pull request merged**
