### PR TITLE
Update fabric8-tenant-jenkins version 4.0.108

### PR DESCRIPTION
**Pull request by piyush1594**
This PR will upgrade the fabric8-tenant-jenkins
version to 4.0.107 which have the fix for following

Issue https://github.com/fabric8io/osio-pipeline/issues/31
PR https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/134

### CODE REVIEW

**Comment by aditya-konarde** [comment]
[test]

**Comment by chmouel** [comment]
[test]

**Comment by aslakknutsen** [comment]
[test]

**Comment by chmouel** [comment]
[test]

**Pull request merged**
