### PR TITLE
oso-proxy commit hash updated with latest master branch commit

### PR DESCRIPTION
**Pull request by nurali-techie**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Oh.. we never rolled the logging thing to prod.. It explains why we don't see it.

**Comment by alexeykazakov** [comment]
[test]

**Comment by nurali-techie** [comment]
> Oh.. we never rolled the logging thing to prod.. It explains why we don't see it.

Yes, this logs were added only for debugging purpose on request of @ibuziuk .. so only kept for `prod-preview`.  Ideally, we no don't need this log on `Info` level.

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
There are e2e tests failures due to pipeline instability (in general there are 7 issues [1] that affect e2e flow) 

[1] https://github.com/openshiftio/openshift.io/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue++label%3Aarea%2Fe2e-tests+

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by nurali-techie** [comment]
FYI, e2e test was failing in my last PR but it was not related to PR changes.
Last PR - https://github.com/openshiftio/saas-openshiftio/pull/1113

I have NOT investigated whether failure for this PR is similar or not.

**Comment by ibuziuk** [comment]
@nurali-techie well, we could force-push in this case, similar to what was done in the PR you mentioned -  https://github.com/openshiftio/saas-openshiftio/pull/1113#issuecomment-432638885

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
@nurali-techie the tests have passed finally, I believe we are good to merge now

**Pull request merged**
