### PR TITLE
Updating Hosted Che to the latest 7.15.1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Upstream issue - https://github.com/eclipse/che/issues/17291

### CODE REVIEW

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[pre-release-tests]

**Pull request merged**
