### PR TITLE
Update fabric8-ui.yaml

### PR DESCRIPTION
**Pull request by jarifibrahim**
# About
This description was generated using this script:
```sh
#!/bin/bash
set -e
GHORG=${GHORG:-fabric8-services}
GHREPO=${GHREPO:-fabric8-wit}
cat <<EOF
# About
This description was generated using this script:
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:

    `echo GHORG=${GHORG} GHREPO=${GHREPO} $(basename $0) ${@:1}`

# Changes
EOF
git log \
  --pretty="%n**Commit:** https://github.com/${GHORG}/${GHREPO}/commit/%H%n**Author:** %an (%ae)%n**Date:** %aI%n%n%s%n%n%b%n%n----%n" \
    --reverse ${@:1} \
  | sed -E "s/([\s|\(| ])#([0-9]+)/\1${GHORG}\/${GHREPO}#\2/g"
```
Invoked as:

    GHORG=fabric8-ui GHREPO=fabric8-ui osio-pull.sh fc37a478011d5190a42656ef0b01059e70336924..upstream/master

# Changes

**Commit:** https://github.com/fabric8-ui/fabric8-ui/commit/fed61e0c1a34a85df6bb7985d8d937efc920b1c4
**Author:** Ibrahim Jarif (jarifibrahim@gmail.com)
**Date:** 2018-09-17T10:09:08+05:30

fix(version): update fabric8-planner to 0.55.10

----

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@sanbornsen @joshuawilson Can you please review? I cannot add you guys as reviewers.

**Comment by jarifibrahim** [comment]
[test]

**Comment by ppitonak** [comment]
Could we skip this update and update directly to 0d534b29b7fe59ae88c7c51c7da08357941b9bc0?

**Comment by jarifibrahim** [comment]
>Could we skip this update and update directly to 0d534b29b7fe59ae88c7c51c7da08357941b9bc0?

I think we can. But since that commit will change fabric8-ui on prod, I'll let @joshuawilson decide if it's ready to be pushed.

**Comment by joshuawilson** [comment]
Please rebase if you still want this.

**Comment by jarifibrahim** [comment]
Closing this in favour of https://github.com/openshiftio/saas-openshiftio/pull/1068.
https://github.com/openshiftio/saas-openshiftio/pull/1068 already has this commit.

**Pull request closed without merging**
