### PR TITLE
add che6 service

### PR DESCRIPTION
**Pull request by riuvshin**
add che6 service
needed for: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1351

@ibuziuk @kbsingh please review

### CODE REVIEW

**Comment by ibuziuk** [comment]
@riuvshin hmmm... I would expect new `rh-che6` entry

**Comment by riuvshin** [comment]
@ibuziuk yeah, that is what I wanted to do initially, but action added by Vasek in the issue sounds like what I've done
```
Add entry in https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/rh-che.yaml which would point to a che6 commit and would carry a name defined to SERVICE_NAME in the job definition
```

**Comment by ibuziuk** [comment]
@riuvshin I think it was a typo and url should be https://github.com/openshiftio/saas-openshiftio/tree/master/dsaas-services / e.g. add new service to dsaas-services. Current PR will not work IMO

**Comment by riuvshin** [comment]
yeah, I was inspired by this https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/f8-jenkins-idler.yaml but, I think you are right, this probably would not work if we will need update che6 separately from che5

**Comment by ibuziuk** [comment]
@riuvshin I have opened https://github.com/openshiftio/saas-openshiftio/pull/670 so this one could be closed now

**Pull request closed without merging**
