### PR TITLE
Deploy latest fabric8-wit master

### PR DESCRIPTION
**Pull request by pranavgore09**
1. Labels
2. Endpoint to create new user via service account

### CODE REVIEW

**Comment by sbose78** [comment]
PR looks good!

Note to the one who merges this, let's please commit this with the message : 

"Add Labels API for planner , and API to create user using a service account"

**Comment by joshuawilson** [comment]
@sbose78 to use that commit message @pranavgore09 needs to rebase and change it.

**Comment by pranavgore09** [comment]
@joshuawilson Is it okay if I amend commit of this branch?

**Comment by sbose78** [comment]
@joshuawilson , could you add the commit message when you merge to master ?

**Pull request merged**
