### PR TITLE
Update Che plugin registry to the latest state

### PR DESCRIPTION
**Pull request by benoitf**
Fix https://github.com/eclipse/che/issues/14138

Change-Id: I01c47f0bb8c8ee588c239b6bb9fa636af582b790
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@benoitf do you happen to know if the latest version of the plugin registry is compatible with the RC 1.1 (the version of che server which is running on prod)?

**Comment by benoitf** [comment]
It is using which URL ? V3 ?

**Comment by ibuziuk** [comment]
> It is using which URL ? V3 ?

yes v3, but on prod we still not using devfiles and workspace are created based on `stacks.json` (currently removed from `rh-che` master) and I suspect this update might break all Che 7 workpaces

**Comment by ibuziuk** [comment]
@benoitf could we postpone plugin registry update till the GA update of che.openshift.io?
I understand that minishift addon still using it, but I believe if we do update right away it will break prod

**Comment by benoitf** [comment]
yes, but predicate ` In fact a registry instance is deployed with every Che deployment now. ` is wrong with minishift addon.

**Comment by benoitf** [comment]
@ibuziuk how it would break `stack.json` ?

diff is there: https://github.com/eclipse/che-plugin-registry/compare/9c87243...master

it only adds new definition of plug-ins and remove v2 and v1 plugins ?

**Comment by ibuziuk** [comment]
@benoitf that is correct, but I always thought that we are going to deprecate the addon (if this is not the case I believe we need to make it consistent and deployable with registries).

>  how it would break stack.json ?

I have not checked this. If it is only v1/v2 cleanup + addition of new plugins (no plugin removals) I believe we can merge it right away

**Comment by benoitf** [comment]
--> @benoitf that is correct, but I always thought that we are going to deprecate the addon (if this is not the case I believe we need to make it consistent and deployable with registries).

well https://github.com/eclipse/che/issues/13889

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@benoitf could you please update commit hash to the latest version of the plugin registry ?

**Comment by benoitf** [comment]
@ibuziuk done

**Comment by benoitf** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by nickboldt** [comment]
For what it's worth, this change has broken the ability to launch Che 7 from within CodeReady Workspaces 1.2.1, as the plugins cannot be loaded now.

The related commit in che-plugin-registry: https://github.com/eclipse/che-plugin-registry/commit/588cf56bc4c08f060520f74fbff584eab325bd83

The supported use case in the CRW 1.2 docs:

https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.2/html-single/administration_guide/index#using-the-che-7-ide-in-codeready-workspaces

The resulting change now required to the CRW 1.2 docs:

https://issues.jboss.org/browse/RHDEVDOCS-1249

So I might argue we should revert this change in che-plugin-registry.openshift.io, and maybe also in in che-plugin-registry... as we're breaking support for existing 1.2 customers. 

If a viable workaround can be created, then it's less urgent to revert. But so far the best I've seen is that the workspace CAN be started, though the dashboard is somewhat broken (can't see anything under the Plugins tab).

**Pull request merged**
