### PR TITLE
Use of new theia (0.3.17)

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: I487d014370f7f2f441d7b26fec9b623bb69a04b3
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
cc @l0rd

**Comment by benoitf** [comment]
@ibuziuk can you launch the tests ?

**Comment by ibuziuk** [comment]
@benoitf yes but those are broken dramatically currently. Trying to grok what is the reason - https://github.com/openshiftio/saas-openshiftio/pull/1160#issuecomment-446145887

**Comment by ibuziuk** [comment]
[e2e-test-released] [e2e-test-beta]

**Comment by ibuziuk** [comment]
[build]

**Comment by ibuziuk** [comment]
[test]

**Comment by benoitf** [comment]
BTW I think the only check for the registry update is that image is able to be built (as it includes some (the only) tests)

**Comment by ibuziuk** [comment]
@l0rd has the power of merging without e2e tests been passed ;-)

**Comment by l0rd** [comment]
@benoitf @ibuziuk merged

**Pull request merged**
