### PR TITLE
[DO NOT MERGE] Updating Hosted Che to the latest '7.24.2' upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/eclipse/che/issues/18792

### CODE REVIEW

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by Katka92** [comment]
Few workspaces were not started during the pre-release tests because of exceeded quota [1].
It also seems that we have a new issue when project explorer is not opened and the test fails waiting for the project to be visible. [2] (I'll create an issue about that)
Taking those failures into account, I don't see any blocker for the release.

[1]
image
[2]
image

**Pull request merged**
