### PR TITLE
Updating che.openshift.io to the latest 7 beta 4 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/redhat-developer/rh-che/issues/1375

### CODE REVIEW

**Comment by ibuziuk** [comment]
Do NOT merge until the plugin registry version is updated in prod cm e.g. https://gitlab.cee.redhat.com/service/app-interface/merge_requests/546/diffs

**Comment by ibuziuk** [comment]
@davidfestal am I correct that no specific cm updates on prod are required for e2e registration flow fix?

**Comment by davidfestal** [comment]
You're right.

**Comment by ibuziuk** [comment]
merge request for updating registry to v2 on prod - https://gitlab.cee.redhat.com/service/app-interface/merge_requests/559/diffs

**Comment by ibuziuk** [comment]
@Katka92 @rhopp @ScrewTSW could you please provide +1 / -1 from QA side ?

**Comment by Katka92** [comment]
@ibuziuk I've run tests and tested few things manually. Both Che 6 and Che 7 workspaces are starting, project imported. Running vert-x Che 6 project works as expected. From my side +1

**Pull request merged**
