### PR TITLE
Update idler to 0292a87

### PR DESCRIPTION
**Pull request by kishansagathiya**

### CODE REVIEW

**Comment by kishansagathiya** [comment]
@chmouel 
e2e tests are failing because of problems occurring during reset environment

```
F    ✗ create_space_new_codebase (1 min 1 sec)
      - Failed: Wait timed out after 60003ms
          at /opt/fabric8-test/node_modules/selenium-webdriver/lib/promise.js:2201:17
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:189:7)
      From asynchronous test: 
      Error
          at Suite.describe (/opt/fabric8-test/src/smoke.spec.ts:69:3)
          at Env.wrapper [as describe] (/opt/fabric8-test/node_modules/jasmine-fail-fast/node_modules/lodash/index.js:3592:19)
          at Object.<anonymous> (/opt/fabric8-test/src/smoke.spec.ts:20:1)
          at Module._compile (module.js:653:30)
          at Object.Module._extensions..js (module.js:664:10)
[06:08:20.600] After all
[06:08:20.604] Reset environment
[06:08:20.609]     Open page CleanupUserEnvPage in RefreshBrowser mode
[06:08:20.610]     Page URL: ****/_cleanup
[06:08:20.614]        Button('Erase My OpenShift.io Environment'): waiting for "clickable"   | timeout: '60000'
(node:79) UnhandledPromiseRejectionWarning: TimeoutError: Wait timed out after 66547ms
    at /opt/fabric8-test/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:79) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
@joshuawilson @aslakknutsen  Is this a known issue?

**Comment by kishansagathiya** [comment]
Can we merge this even though e2e tests are failing, this would help stabilize the problems this [sev1](https://github.com/openshiftio/openshift.io/issues/4422) is creating

How would this change help? quoting @sthaha from hk ticket
> I see majority of pods are associated with prod instead of prod-preview, so part of the change I made to idler (deployed to prod) has helped. But there is one more patch that should go in. 

The changes added includes @sthaha 's change to not unidle jenkins on a dc change

**Comment by ljelinkova** [comment]
The e2e tests failed because the menu item has been renamed. We will provide fix ASAP.

**Comment by chmouel** [comment]
Merging: /related https://chat.openshift.io/developers/pl/y9jazjmjci8y9mre1oc88sn8jw

**Comment by chmouel** [comment]
@ljelinkova can you please let us know when this is done so we can mege this asap ? (as per last email about E2E on saas)

**Comment by ppitonak** [comment]
@chmouel I'll start PR checks as soon as new version of tests are ready

**Comment by riuvshin** [comment]
[test]

**Comment by ppitonak** [comment]
@riuvshin PR checks are expected to fail, new version of tests is not ready yet

**Comment by riuvshin** [comment]
[test]

**Pull request merged**
