### PR TITLE
Updating rh-che to the latest 7 beta 1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
https://github.com/redhat-developer/rh-che/issues/1254

### CODE REVIEW

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
@l0rd I believe we would need a force push after QA approval cc: @rhopp

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
@ppitonak keep failing with `Failed: App tag is present` - if the e2e tests are officially dead, why not to remove those deta / released checks at all to avoid misleading?

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ScrewTSW** [comment]
CC https://github.com/redhat-developer/rh-che/issues/1254#issuecomment-471885859

Same experience. Everything seems to work fine, however 2a cluster has issues with very slow project import (namely vert-x stack). I think we are green to go with the update.

**Comment by rhopp** [comment]
> @ppitonak keep failing with `Failed: App tag is present` - if the e2e tests are officially dead, why not to remove those deta / released checks at all to avoid misleading?

I'm +1 for removing these checks from here. That means we will have some window, where there will be no PR check in this repository, until we create new jobs with just che tests. But because current E2E tests are failing in (almost?) 100% cases, having period in time where no quality gate will be here is not a big issue.

**Comment by ibuziuk** [comment]
@l0rd could you please force push ?

**Comment by ppitonak** [comment]
> > @ppitonak keep failing with `Failed: App tag is present` - if the e2e tests are officially dead, why not to remove those deta / released checks at all to avoid misleading?
> 
> I'm +1 for removing these checks from here. That means we will have some window, where there will be no PR check in this repository, until we create new jobs with just che tests. But because current E2E tests are failing in (almost?) 100% cases, having period in time where no quality gate will be here is not a big issue.

Done https://github.com/openshiftio/openshiftio-cico-jobs/pull/983

**Pull request merged**
