### PR TITLE
Updates f8-tenant: fixes plugin storage size issue and updates bayesian plugin (vb355188)

### PR DESCRIPTION
**Pull request by hrishin**
This patch
- updates jenkins configuration to reduces the plugins storage
space required for each tenant jenkins. (fix#1)
- update bayesian jenkins plugin to 0.3.3 which has
enhancements to support osio-pipeline. (fix#2)

Updates f8-tenant image: vb355188

Fixes
    - openshiftio/openshift.io#4568
    - https://openshift.io/openshiftio/Openshift_io/plan/detail/1216

### CODE REVIEW

**Comment by hrishin** [comment]
@chmouel could you please merge this?

**Comment by piyush-garg** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by piyush-garg** [comment]
[e2e-test-beta]

**Comment by piyush-garg** [comment]
[e2e-test-beta]

**Comment by piyush-garg** [comment]
@chmouel We are good now. cc @hrishin 

And we need tenant update also after this.

**Pull request merged**
