### PR TITLE
[DO NOT MERGE] Update Che plugin registry

### PR DESCRIPTION
**Pull request by amisevsk**

### CODE REVIEW

**Comment by amisevsk** [comment]
cc: @ibuziuk @Katka92 @screwTSW

This update removes editor `eclipse/che-theia/7.0.0-next` which may cause issues -- it's hard to know where this image is used. It's also necessary for the 7.0.0 rollout I believe.

**Comment by Katka92** [comment]
Regarding tests - these are failing on Language server validation. This is known issue https://github.com/redhat-developer/rh-che/issues/1565 and is not caused by this PR.

**Comment by ibuziuk** [comment]
@amisevsk hmm.. not following why do we need to update plugin registry at all? che.openshift.io is running against RC 1.1 with compatible plugin registry? My plan was to update both che server and che-plugin registry simultaneously

**Comment by ibuziuk** [comment]
ok, I figure out what is the issue - https://github.com/eclipse/che/issues/14261 but we need more details from reporter

**Pull request closed without merging**
