### PR TITLE
Update che-plugin-registry to 016b2cded99c7b06e6ba456965fde4dcf0c00b5c

### PR DESCRIPTION
**Pull request by l0rd**
cc @skabashnyuk @riuvshin

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
@rhopp any idea why e2e tests randomly failed? and why it is mandatory checks now

**Comment by riuvshin** [comment]
[test]

**Pull request merged**
