### PR TITLE
Updating che to upstream 6.10.0 version

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@rhopp please, let me know when prod-preview testing is finished

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk All test failures were my fault, Rh-Che 6.10.0 is OK :+1: You can proceed with update. Thanks!

**Comment by ibuziuk** [comment]
@Katka92 thanks for update. Merging

**Pull request merged**
