### PR TITLE
Update che-plugin-registry

### PR DESCRIPTION
**Pull request by l0rd**
Update to version c9df13b9bb53cf1f4c7e5152a3526b263be6be56

### CODE REVIEW

**Comment by l0rd** [comment]
@benoitf please review

**Comment by benoitf** [comment]
@l0rd I'm not sure of these messages
```
+ python /home/devtools/saasherder/check_image.py /home/devtools/workspace/devtools-saas-openshiftio-promote-to-prod-test/dsaas-20181019_153013/che-plugin-registry.yaml '^quay\.io/openshiftio/rhel-'
time="2018-10-19T15:30:48Z" level=fatal msg="Error reading manifest af5280f in quay.io/openshiftio/rhel-che-plugin-registry: manifest unknown: manifest unknown" 
Could not find image quay.io/openshiftio/rhel-che-plugin-registry:af5280f in registry
```

**Comment by benoitf** [comment]
@l0rd AFAIK it's you that set this hash
while I don't find it there
https://quay.io/repository/openshiftio/che-plugin-registry?tab=tags

**Comment by l0rd** [comment]
@benoitf that should be the hash of the last commit in the git repository. Not the container image hash

**Comment by l0rd** [comment]
@benoitf sorry, the hash should be the same and true we still haven't built the image related to the last commit. Weird. Need to check the build.

**Pull request merged**
