### PR TITLE
che-tenant-maintainer pulling from quay for staging

### PR DESCRIPTION
**Pull request by jmelis**
Changes the container image to be pulled from Quay. Since this is for the staging environment, it should not affect production.

Any subsequent PRs to the project's repo will fail unless the CICO build scripts are pushing the container image to Quay.

A companion PR will be submitted to the project's repo to make the CICO build scripts push to Quay. Merge the project's repo PR only after merging this one.

### CODE REVIEW

**Comment by ibuziuk** [comment]
@davidfestal could you please take a look ^ ?

**Comment by davidfestal** [comment]
@ibuziuk yes, I'm looking into it

**Comment by davidfestal** [comment]
@jmelis is there an example of the changes I should implement in the cico build scritps to make them push to Quay.io ?

**Comment by jmelis** [comment]
I submitted this PR yesterday with the changes to the build scripts: https://github.com/fabric8-services/che-tenant-maintainer/pull/21/files

**Pull request merged**
