### PR TITLE
Updating plugin registry to the latest version

### PR DESCRIPTION
**Pull request by ibuziuk**
Should fix - https://github.com/eclipse/che/issues/12631

### CODE REVIEW

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
@ldimaggi @ppitonak could you please delete all existing workspace from e2e test account. According to @rhopp it might be the reason of failing tests (AFAIK test account has more than 60 workpaces created)

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ppitonak** [comment]
E2E tests fail on https://github.com/openshiftio/openshift.io/issues/4695 and https://github.com/openshiftio/openshift.io/issues/4752

**Comment by ppitonak** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ppitonak** [comment]
Last job failed because of https://github.com/openshiftio/openshift.io/issues/4696

**Comment by ppitonak** [comment]
@ibuziuk last two jobs failed on pipeline (#4752) so IMHO it's safe to merge your PR.

**Comment by ibuziuk** [comment]
@l0rd could you please force push ?

**Pull request merged**
