### PR TITLE
updates idler : logging changes

### PR DESCRIPTION
**Pull request by hrishin**
Recently during update tenant, idler has experienced unusual
activity, hence to get more insights, log verbosity
has been increased.
This patch reduces the logging verbosity.

Related
 - https://github.com/fabric8-services/fabric8-jenkins-idler/issues/315

### CODE REVIEW

**Comment by hrishin** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by hrishin** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by hrishin** [comment]
@chmouel E2E tests are failing because of the timeout. Shall we go this patch in?

**Comment by hrishin** [comment]
@chmouel this has go in, can we do that? so our prod-preview and prod idler would be consistent.

Not sure why these tests failing with timeout error.

**Comment by chmouel** [comment]
We really need to implement this instead : https://github.com/fabric8-services/fabric8-jenkins-idler/issues/323  restarting the idler/proxy pods, doesn't give us overview of what is the current issue, 

(and i can't merge this without CI passing)

**Comment by hrishin** [comment]
@chmouel, I second that (bad option though), it would be a new feature implementation.  
For the time being, we have to get this PR in.

Its E2E tests are failing because

```
e2e_smoketest > run_che
Failed: Wrong number of projects in Che (expected 1). It could mean that Che workspace failed to start, check che-failed.png and oc-che-logs.txt.
Wait timed out after 600000ms
```

@alexeykazakov could you please merge this as well? 
Thank you!

**Pull request closed without merging**
