### PR TITLE
Enforce 6 char len for image tag

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by joshuawilson** [comment]
Can we still use the full string or is this only up to 6?

**Comment by vpavlin** [comment]
TL;DR; Nothing changes for you, @joshuawilson 

The `hash` value is still going to be full commit length...this is just a temporary setting for image tag length (`fabric8-ui:aaaaaa`) because the default will be switched to 7 to follow git best practices...so to avoid failed deploys, I'll enforce 6 for now through the per-service configuration. Then we'll switch to 7 on one-by-one base.

**Comment by joshuawilson** [comment]
cool, thanks

**Comment by vpavlin** [comment]
[test]

**Comment by vpavlin** [comment]
[test]

**Comment by vpavlin** [comment]
[test]

**Pull request merged**
