### PR TITLE
[DO NOT MERGE] Updating Hosted Che to the latest 7.17.2 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Upstream issue - https://github.com/eclipse/che/issues/17676

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Pull request merged**
