### PR TITLE
updates fabric8-ui.yaml with env for jenkins/build url

### PR DESCRIPTION
**Pull request by invincibleJai**
- updates fabric8-ui.yaml with env for jenkins/build url

Tracks https://github.com/openshiftio/openshift.io/issues/3356#issuecomment-396562994

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by invincibleJai** [comment]
@joshuawilson builds are failing, is there something else I need to do?

**Comment by joshuawilson** [comment]
@jfchevrette any idea why this isn't building?

**Comment by jfchevrette** [comment]
This adds parameter 'fabric8_jenkins_api_url' for saasherder to process but that parameter is not in the template at: https://github.com/fabric8-ui/fabric8-ui/blob/master/openshift/fabric8-ui.app.yaml

**Comment by joshuawilson** [comment]
I didn't think I saw that added. Didn't know it needed to be there first, but that makes sense. 

@invincibleJai do you have a PR that adds this env var to f8-ui?

**Comment by invincibleJai** [comment]
thanks @joshuawilson will add a PR for that, was not aware of that.

**Comment by invincibleJai** [comment]
@joshuawilson have raised a PR https://github.com/fabric8-ui/fabric8-ui/pull/3041 , pls take a look.

**Comment by joshuawilson** [comment]
[test]

**Comment by invincibleJai** [comment]
[test]

**Comment by invincibleJai** [comment]
@jfchevrette  @joshuawilson still build is failing with error `error: unknown parameter name "fabric8_jenkins_api_url"` 

As suggested have updated https://github.com/fabric8-ui/fabric8-ui/blob/master/openshift/fabric8-ui.app.yaml#L68 

any help with what I missed?

**Comment by joshuawilson** [comment]
I know what it is. We need to include the build of f8-ui that has the needed changes. Let me push to prod and then when you rebase it should work.

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
