### PR TITLE
Update www.openshift.io.yaml

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@alexeykazakov @joshuawilson 
This PR push in production:
https://github.com/openshiftio/openshift.io/issues/4162 (forward to new gettingstarted documentation)

**Comment by joshuawilson** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
