### PR TITLE
Updating che to the 6.13.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW @Katka92 could you please do some testing on prod-preview before we merge this PR.
@ppitonak is it currently expected that e2e are failing due to pipeline ?

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
e2e tests are passing. Waiting for +1 from QA before merging to prod.

**Comment by ppitonak** [comment]
@ibuziuk you need to read the manual :) Pipeline is still unstable because of #4215

**Comment by ibuziuk** [comment]
@ppitonak could you please point me to the manual, wondering why the manual is not part of the repo's readme ?

**Comment by Katka92** [comment]
@ibuziuk We've tested it and seems OK. :+1:

**Comment by ibuziuk** [comment]
Thanks for verifying. Promoting to prod

**Pull request merged**
