### PR TITLE
Updating che-tenant-maintainer to the latest version (using RHEL based image for prod)

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@davidfestal @riuvshin are you ok to merge ?

**Comment by davidfestal** [comment]
I didn't test it fully TBH.

**Comment by ibuziuk** [comment]
@davidfestal are you going to do quick test before promoting to prod ?

**Comment by davidfestal** [comment]
tests were OK. You can merge this

**Pull request merged**
