### PR TITLE
[WIP] Dummy PR to test PR check

### PR DESCRIPTION
**Pull request by Katka92**
A new PR check was added by this PR: https://github.com/openshiftio/openshiftio-cico-jobs/pull/994
This PR servers for testing it. Once PR will works correctly, this PR would be closed.

### CODE REVIEW

**Comment by Katka92** [comment]
[tesŧ]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[tes]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[tes]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
PR check for RH-Che seems to be working correctly now. Closing this PR.

**Pull request closed without merging**
