### PR TITLE
use che plugin registry id before 0.3.17 of theia

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: I45ff6220ca7d75a168e87bbd87643a9edcb3ce29
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[e2e-test-released] [e2e-test-beta]

**Comment by benoitf** [comment]
cc @l0rd :-)

**Pull request merged**
