### PR TITLE
Reduce verbosity level of logs

### PR DESCRIPTION
**Pull request by khrm**
Set the verbosity of the log to "warning" as idler currently is
logging more than 12million records a day.

Fixes https://github.com/fabric8-services/fabric8-jenkins-idler/issues/310

### CODE REVIEW

**Comment by sthaha** [comment]
[test]

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by riuvshin** [comment]
[e2e-test-beta]
[e2e-test-released]

**Pull request merged**
