### PR TITLE
Updating Hosted Che to the latest 7.20.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
upstream issue - https://github.com/eclipse/che/issues/18058

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Comment by ibuziuk** [comment]
[pre-release-tests]

**Pull request merged**
