### PR TITLE
Update Idler with back-off feature for idling and un-idling

### PR DESCRIPTION
**Pull request by hferentschik**
Includes fix for https://github.com/fabric8-services/fabric8-jenkins-idler/issues/133. 
Idler now has a max retry for idling and un-idling.

### CODE REVIEW

**Comment by hferentschik** [comment]
Let's sync the merge of this. The plan is to handhold and monitor Idler when we enable this. Once this is merged and deployed we need to enable the Idler feature again in Unleash to get the actual idling happening again.

**Comment by kbsingh** [comment]
can we target 2pm UTC ?

**Comment by hferentschik** [comment]
I'd prefer a bit earlier. Can we make it 12pm?

**Comment by hferentschik** [comment]
thanks

**Pull request merged**
