### PR TITLE
Update docs to fix landing page.

### PR DESCRIPTION
**Pull request by rkratky**

### CODE REVIEW

**Comment by rkratky** [comment]
Thanks @jarifibrahim. I'm not sure it'll fix the problem. According to the log, the test is looking for the following image:

quay.io/openshiftio/rhel-fabric8io-fabric8-online-docs:a32c66d

(i.e. with "rhel-" in the name)

**Comment by jarifibrahim** [comment]
> Thanks @jarifibrahim. I'm not sure it'll fix the problem. According to the log, the test is looking for the following image:
> 
No no. The actual issue was that you created this PR before the image was pushed to quay. 

> quay.io/openshiftio/rhel-fabric8io-fabric8-online-docs:a32c66d
> 
> (i.e. with "rhel-" in the name)

For `rhel-` images, look at https://ci.centos.org/job/devtools-fabric8-online-docs-build-master/246/console
```
+ docker push quay.io/openshiftio/rhel-fabric8io-fabric8-online-docs:a32c66d
```
The `rhel-` images aren't visible on https://quay.io/repository/openshiftio/fabric8io-fabric8-online-docs?tab=tags because these images are private (I'm guessing).

**Comment by rkratky** [comment]
@jarifibrahim, looks like you're right, but the tests are now failing because of what to me looks like a problem with the app.

**Comment by jarifibrahim** [comment]
@ppitonak looks like the e2e tests are failing due to some strange reason. Shall we merge this PR or is someone working on fixing these tests?

**Comment by ppitonak** [comment]
@jarifibrahim yes, it's a bug in tests, feel free to ignore... it seems that fix merged this morning didn't help :(

**Comment by jarifibrahim** [comment]
>@jarifibrahim yes, it's a bug in tests, feel free to ignore... it seems that fix merged this morning didn't help :(

Thanks @ppitonak.

@rkratky We can merge this PR.

**Comment by Preeticp** [comment]
Thank you @joshuawilson

**Pull request merged**
