### PR TITLE
Deploy latest rh-che changes to prod

### PR DESCRIPTION
**Pull request by amisevsk**
Rollout to include https://github.com/redhat-developer/rh-che/commit/c52d64dc9bf8836e7194b9a736d0ef27c7364694

### CODE REVIEW

**Comment by amisevsk** [comment]
[test]

**Comment by Katka92** [comment]
There was a test failure because the testing file was changed. Fix for the test was applied, rerunning.

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Pull request merged**
