### PR TITLE
Update auth to 16c631

### PR DESCRIPTION
**Pull request by xcoulon**
Include fixes to 
- allow for assigning role to user again (https://github.com/fabric8-services/fabric8-auth/commit/16c631f5090d678b3f2d95eb654b90f3afe2ef1b) 
- login redirect (https://github.com/fabric8-services/fabric8-auth/commit/923e7a3b3c16569b1d52e42fdd7fd930bed73f3c)

### CODE REVIEW

**Comment by joshuawilson** [comment]
I think it is a different command to re-run the e2e tests.

**Comment by alexeykazakov** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by xcoulon** [comment]
[test-e2e]

**Comment by xcoulon** [comment]
[e2e-test-beta]

**Comment by ppitonak** [comment]
[e2e-test-released]

**Comment by ppitonak** [comment]
[e2e-test-beta] [e2e-test-released]

**Pull request merged**
