### PR TITLE
add build tool detector api url

### PR DESCRIPTION
**Pull request by vikram-raj**
related to https://github.com/fabric8-ui/fabric8-ui/pull/3476

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by aditya-konarde** [comment]
[do-not-merge]

I had a discussion with @vikram-raj and @jarifibrahim ; The better way to do this is via a configmap. I've added a key to the preview configmap and Vikram is currently testing it.

**Comment by jarifibrahim** [comment]
We've merged https://github.com/fabric8-ui/fabric8-ui/pull/3488 to use value from config map.

**Comment by aditya-konarde** [comment]
Closing as this is no longer needed, since the value is now imported via a config map.

@jarifibrahim @vikram-raj should also see if the other values in the template can be deleted/used via a configmap

**Pull request closed without merging**
