### PR TITLE
Updating rh-che to 7.3.0

### PR DESCRIPTION
**Pull request by ibuziuk**
Related issue - https://github.com/eclipse/che/issues/14656

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
Tests are failing because of known problems with LS initialization. Other tests are passing continuously, so if you are OK with this issue, you can merge.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
Hosted che update is postponed due to #14944
we are going to update prod with 7.3.1 where the regression is fixed

**Pull request closed without merging**
