### PR TITLE
Updates jenkins tenant : a0f86aa

### PR DESCRIPTION
**Pull request by hrishin**
This patch reduces the plugins storage space required
for each tenant jenkins

Fixes
 - https://github.com/openshiftio/openshift.io/issues/4568

### CODE REVIEW

**Comment by hrishin** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by ppitonak** [comment]
PR checks failed because of https://github.com/openshiftio/openshift.io/issues/4634 therefore I think that it's safe to merge.

**Comment by hrishin** [comment]
Thank you @ppitonak 

@MatousJobanek could you please help us to get this merge?

**Comment by ppitonak** [comment]
[e2e-test-beta] [e2e-test-released]

**Pull request merged**
