### PR TITLE
Updating oso-proxy to the latest version

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by ibuziuk** [comment]
cc: @nurali-techie

**Comment by ibuziuk** [comment]
[e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-released]

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-released]

**Comment by ibuziuk** [comment]
@ppitonak  any idea why the e2e are constantly failing with:

```
Will not overwrite target file: 'jenkins-env.json'. Use --force.
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (1/5)
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (2/5)
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (3/5)
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (4/5)
The requested operation failed as no inventory is available.
'cico node get' failed, trying again in 60s (5/5)
The requested operation failed as no inventory is available.
giving up on 'cico node get'
```

**Comment by ibuziuk** [comment]
@riuvshin am I correct that this is related to `duffy fails to give nodes on devtools slave04` ?

**Comment by ppitonak** [comment]
@ibuziuk they can't get a Duffy node to test on. It's infra issue, not a problem with e2e tests. SD team knows about that.

**Comment by ibuziuk** [comment]
[e2e-test-beta]

**Comment by ibuziuk** [comment]
[e2e-test-released]

**Comment by ppitonak** [comment]
[e2e-test-released]

@ibuziuk FYI, you can trigger both e2e jobs in one comment, the regexp should handle that

**Comment by ibuziuk** [comment]
@ppitonak thanks, great tip

**Pull request merged**
