### PR TITLE
Add f8build service

### PR DESCRIPTION
**Pull request by chmouel**
This closes fabric8-services/fabric8-build#32 and closes
openshiftio/openshift.io#4444

### CODE REVIEW

**Comment by chmouel** [comment]
Need this to be merged https://github.com/fabric8-services/fabric8-build/pull/50

**Comment by chmouel** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by chmouel** [comment]
@ppitonak @ljelinkova

**Comment by chmouel** [comment]
[e2e-test-beta]
[e2e-test-released]

**Comment by ppitonak** [comment]
@chmouel IMHO it could be related to expired certificate on starter-us-east-2a

**Pull request merged**
