### PR TITLE
Update che plugin registry

### PR DESCRIPTION
**Pull request by skabashnyuk**
Changes

* 717caab 2018-11-05 | Change type of Eclipse Dirigible for Eclipse Che to Che Editor (#56) (HEAD -> master, origin/master) [Sergii Kabashniuk]
* 623ab9a 2018-11-05 | Adding dirigible-che-editor-plugin (#54) [Nedelcho Delchev]
* 17e5911 2018-10-24 | Added gwt based ide definition (#47) (dirigible) [Sergii Kabashniuk]

### CODE REVIEW

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
[test]

**Comment by ppitonak** [comment]
[e2e-test-beta] [e2e-test-released]

**Comment by ppitonak** [comment]
[e2e-test-released]

**Comment by ppitonak** [comment]
PR check failed because of https://github.com/openshiftio/openshift.io/issues/4517, IMHO completely unrelated to this PR

**Pull request merged**
